### ISSUE TITLE
Incorrect Value for ErfuellendeGemeinde in Line 19

### ISSUE THREAD

**Issue by buba9912** [podolsir/python-gemeindeverzeichnis#1]
In line 19 the variable ErfuellendeGemeinde is set to an incorrect value.

https://github.com/podolsir/python-gemeindeverzeichnis/blob/0eae5d311006c8da8093ea46b1a07491718ee88a/gemeindeverzeichnis.py#L19

Current state (is):
ErfuellendeGemeinde = 68

Expected state (should):
ErfuellendeGemeinde = 58

https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/beschreibung-gebietseinheiten.pdf?__blob=publicationFile

PS: Thanks for the help, saved me time!

**Comment by podolsir** [comment]
Fixed it in version 0.3.
You're welcome :) To be honest, I am absolutely astonished that someone actually uses this little library.
